apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nextjs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nextjs
    spec:
      containers:
        - name: nextjs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
