apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextjs
spec:
  type: LoadBalancer  # または NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-nextjs